development:
  adapter: postgresql
  database: marketInspector_development
  username: marketInspector
  password: marketInspector
  host: localhost

test:
  adapter: postgresql
  database: marketInspector_test
  username: marketInspector
  password: marketInspector
  host: localhost
